kind: Rules
metadata:
  namespace: k8s-tutorial
spec:
  - name: "k8s.AddEnvAppLabels"
    description: "Adding environment and application labels using context information from Deploy"
    condition:
      deployedType: helm.K8SRelease
      expression: "#input.getStringValue('$.kind') == 'Secret'" # activate only for kind:Service
      expression: "#input.getStringValue('$.data.tomcat-password') == 'c2NvdHQ='"
    processor:
       - type: freemarker
         description: "Adding label to kubernetes spec"
         phase: POST_FLIGHT
         weight: 30
         merge:
           type: overlay
         parameters:
           template: |

